{"name": "test_login[inBody1-exspData1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '输入的密码错误!' == '输入的密码错误'\n  - 输入的密码错误\n  + 输入的密码错误!\n  ?        +", "trace": "self = <test_case.test_login.Test_login object at 0x00000245167C69B0>\ninBody = {'password': 11212, 'username': 'th0479'}\nexspData = {'code': 9999, 'msg': '输入的密码错误'}\n\n    @pytest.mark.parametrize(\"inBody,exspData\",get_yamla_case_data(\"../data/data.yaml\"))  # 数据驱动固定语法，首先两个变量名然后赋\n    def test_login(self,inBody,exspData):\n        res = Login().login(inBody)\n        #调用登录接口代码\n        #做断言：\n        print(\"--正在执行--\")\n>       assert res[\"msg\"] == exspData[\"msg\"]\nE       AssertionError: assert '输入的密码错误!' == '输入的密码错误'\nE         - 输入的密码错误\nE         + 输入的密码错误!\nE         ?        +\n\ntest_login.py:21: AssertionError"}, "parameters": [{"name": "inBody", "value": "{'username': 'th0479', 'password': 11212}"}, {"name": "exspData", "value": "{'code': 9999, 'msg': '输入的密码错误'}"}], "start": 1626677565325, "stop": 1626677565371, "uuid": "1445c918-0f5c-4c62-b794-611f9a8b9557", "historyId": "08f9ad289a7d8dee7bc420b86d54e259", "testCaseId": "545159219aea40d38c768fae9108b043", "fullName": "test_case.test_login.Test_login#test_login", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "LAPTOP-AGJMADVL"}, {"name": "thread", "value": "10720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login"}]}